name: aabim
channels:
  - conda-forge
  - ocdb
dependencies:
  - python
  - black
  - numpy
  - cupy
  - scipy
  - dask
  - netCDF4
  - h5py
  - gdal
  - pyproj
  - pandas
  - pooch
  - geopandas
  - tqdm
  - timezonefinder
  - pendulum
  - charset-normalizer
  - shapely
  - statsmodels
  - xarray
  - zarr
  - affine
  - rasterio
  - ipykernel
  - pip
  - pip:
    - p_tqdm
    - pylr2
